### ISSUE TITLE
IBSI feature correspondence

### ISSUE THREAD

**Issue by fedorov** [pwoznicki/AutoRadiomics#34]
For the purposes of harmonization and to enable comparisons across toolkits (e.g., against pyradiomics), it would be quite helpful if there was assignment of IBSI codes to those features that match the definitions in https://arxiv.org/abs/1612.07003. Did you consider doing something like this?

**Comment by fedorov** [comment]
I did not realize that this tool seems to wrap pyradiomics for the purposes of feature extraction. You might want to point this out in the front page readme.

**Comment by laqua-stack** [comment]
@fedorov Sorry, I must have missed the message when you opened this issue. 
You are right. The info is in our paper but should be added in the Readme aswell. 
I will reopen this issue.
